import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const src = (title, url, type = 'government') => ({ title, url, doi: null, type });

const claims = [
  {
    id: 'wealth-inequality-broken',
    topicId: 'wealth-inequality-mobility',
    title: 'Wealth Inequality Proves Capitalism Is Broken',
    socialistClaim: 'Rising wealth inequality proves capitalism is fundamentally broken and immoral.',
    executiveSummary: 'Relative inequality metrics tell us nothing about absolute living standards without context. The U.S. bottom quintile real consumption has risen dramatically since 1960 while global extreme poverty collapsed under market integration. Inequality can rise while everyone gets richer.',
    evidenceBullets: ['CBO: bottom quintile real consumption +60% (1960-2019)', 'World Bank: extreme poverty 36% to ~8.5% (1990-2022)', 'Chetty: ~7.5% of bottom-quintile children reach top quintile'],
    fallacies: ['zero-sum thinking', 'confusing relative with absolute'],
    sources: [src('CBO Income Distribution', 'https://www.cbo.gov/topics/income-distribution'), src('World Bank Poverty', 'https://www.worldbank.org/en/topic/poverty'), src('Chetty Mobility', 'https://opportunityinsights.org/', 'academic')],
    whyItMatters: 'America debates envy metrics instead of mobility and poverty reduction.',
    relatedClaimIds: ['consumption-vs-income', 'billionaires-shouldnt-exist'],
    tags: ['inequality', 'wealth', 'gini', 'mobility'],
  },
  {
    id: 'consumption-vs-income',
    topicId: 'wealth-inequality-mobility',
    title: 'Income Inequality Equals Material Deprivation',
    socialistClaim: 'The poor are getting poorer because the income gap is widening.',
    executiveSummary: 'Income snapshots ignore taxes, transfers, household size, and lifecycle effects. Consumption inequality is far narrower than income inequality in the U.S.',
    evidenceBullets: ['Meyer & Sullivan: consumption inequality narrower than income', 'BLS CEX: broad durable goods access at lower incomes', 'Transfers materially raise bottom-quintile resources'],
    fallacies: ['static snapshot fallacy'],
    sources: [src('BLS Consumer Expenditure Survey', 'https://www.bls.gov/cex/')],
    whyItMatters: 'Political rhetoric uses pre-tax income to manufacture crises consumption data does not support.',
    relatedClaimIds: ['wealth-inequality-broken'],
    tags: ['consumption', 'income', 'poverty'],
  },
  {
    id: 'gini-misused',
    topicId: 'wealth-inequality-mobility',
    title: 'The Gini Coefficient Proves Unfairness',
    socialistClaim: "America's Gini coefficient proves our system is unfair.",
    executiveSummary: 'Gini measures dispersion, not injustice. Mixed economies with heavy transfers can share similar Ginis while differing in growth and mobility.',
    evidenceBullets: ['Heritage: economic freedom correlates with prosperity', 'Gini ignores transfers and household composition'],
    fallacies: ['metric fixation'],
    sources: [src('Heritage Index of Economic Freedom', 'https://www.heritage.org/index/', 'think_tank')],
    whyItMatters: 'Policy-by-Gini replaces serious analysis of institutions and opportunity.',
    relatedClaimIds: ['wealth-inequality-broken'],
    tags: ['gini', 'inequality'],
  },
  {
    id: 'mobility-dead',
    topicId: 'wealth-inequality-mobility',
    title: 'The American Dream Is Dead',
    socialistClaim: 'Poor Americans are stuck with no upward mobility.',
    executiveSummary: 'Mobility varies by county and policy environment. Family structure, schools, and economic freedom predict outcomes more than slogans.',
    evidenceBullets: ['Chetty: county-level mobility variation', 'Fraser: freer economies grow faster'],
    fallacies: ['anecdotal generalization'],
    sources: [src('Opportunity Insights', 'https://opportunityinsights.org/', 'academic')],
    whyItMatters: 'Declaring mobility dead discourages the institutional reforms that actually help.',
    relatedClaimIds: ['wealth-inequality-broken'],
    tags: ['mobility', 'american dream'],
  },
  {
    id: 'billionaires-shouldnt-exist',
    topicId: 'wealth-inequality-mobility',
    title: "Billionaires Shouldn't Exist",
    socialistClaim: 'No one should have a billion dollars while others starve.',
    executiveSummary: 'Wealth at scale often reflects value creation. Poverty is addressed by growth and institutions, not wealth caps that drive away capital.',
    evidenceBullets: ['World Bank: global poverty fell during era of tech wealth creation', 'Tax Foundation: wealth tax revenue and capital flight risks'],
    fallacies: ['appeal to envy', 'zero-sum thinking'],
    sources: [src('World Bank', 'https://www.worldbank.org/'), src('Tax Foundation', 'https://taxfoundation.org/', 'think_tank')],
    whyItMatters: 'Envy-driven policy risks the investment that creates jobs for ordinary Americans.',
    relatedClaimIds: ['wealth-inequality-broken', 'profit-is-theft'],
    tags: ['billionaires', 'wealth', 'tax'],
  },
  {
    id: 'poverty-racism-only',
    topicId: 'wealth-inequality-mobility',
    title: 'Poverty Is Only Structural Racism',
    socialistClaim: 'Capitalism and racism are the same system causing poverty.',
    executiveSummary: 'Racial gaps are real but respond to opportunity-expanding reforms and market participation, not collectivization.',
    evidenceBullets: ['Census: ethnic income trend data', 'SBA: minority business growth statistics'],
    fallacies: ['single-cause fallacy'],
    sources: [src('U.S. Census Bureau', 'https://www.census.gov/')],
    whyItMatters: 'Oversimplified narratives block bipartisan institutional fixes.',
    relatedClaimIds: ['wealth-inequality-broken'],
    tags: ['racism', 'poverty', 'inequality'],
  },
  {
    id: 'profit-is-theft',
    topicId: 'profit-exploitation',
    title: 'Profit Is Theft From Workers',
    socialistClaim: 'Profit is surplus value stolen from workers.',
    executiveSummary: 'Profit compensates uncertainty, coordination, and innovation. Competitive markets compress excess returns. Value is subjective, not embedded labor-hours.',
    evidenceBullets: ['Mises: prices coordinate dispersed knowledge', 'Competitive entry compresses abnormal profits'],
    fallacies: ['labor theory of value', 'zero-sum thinking'],
    sources: [src('Mises Institute', 'https://mises.org/', 'academic')],
    whyItMatters: 'Anti-profit rhetoric undermines the incentive structure that raises wages via productivity.',
    relatedClaimIds: ['exploitation-marx', 'worker-coops-superior'],
    tags: ['profit', 'exploitation', 'marx'],
  },
  {
    id: 'exploitation-marx',
    topicId: 'profit-exploitation',
    title: 'Workers Are Exploited Under Capitalism',
    socialistClaim: 'Capitalists exploit workers by paying less than value created.',
    executiveSummary: 'Voluntary exchange, consumer surplus, and capital deepening raise marginal product. Real compensation tracks productivity where markets function.',
    evidenceBullets: ['BEA: labor productivity data', 'BLS: compensation-productivity correlation'],
    fallacies: ['labor theory of value'],
    sources: [src('Bureau of Economic Analysis', 'https://www.bea.gov/'), src('Bureau of Labor Statistics', 'https://www.bls.gov/')],
    whyItMatters: 'Exploitation framing replaces negotiation, mobility, and entrepreneurship as paths upward.',
    relatedClaimIds: ['profit-is-theft'],
    tags: ['exploitation', 'workers', 'wages'],
  },
  {
    id: 'rich-get-richer-poor-poorer',
    topicId: 'profit-exploitation',
    title: 'The Rich Get Richer, Poor Get Poorer',
    socialistClaim: 'Under capitalism the rich always get richer while the poor get poorer.',
    executiveSummary: 'Both groups can rise simultaneously. Census and World Bank data show rising real incomes at the bottom over decades.',
    evidenceBullets: ['Census: real median household income records', 'World Bank: global poverty decline since 1990'],
    fallacies: ['zero-sum thinking'],
    sources: [src('U.S. Census Bureau', 'https://www.census.gov/'), src('World Bank', 'https://www.worldbank.org/')],
    whyItMatters: 'Zero-sum myths justify redistribution that can shrink the pie for everyone.',
    relatedClaimIds: ['wealth-inequality-broken'],
    tags: ['rich', 'poor', 'zero-sum'],
  },
  {
    id: 'worker-coops-superior',
    topicId: 'profit-exploitation',
    title: 'Worker Cooperatives Prove Socialism Works',
    socialistClaim: 'Co-ops outperform capitalist firms and prove socialism.',
    executiveSummary: 'Co-ops thrive in niches but face capital and scale constraints. Their existence proves market pluralism, not abolition of private ownership.',
    evidenceBullets: ['Mondragon: successful but limited scale model', 'VC-backed firms drive large-scale innovation'],
    fallacies: ['hasty generalization'],
    sources: [src('Mondragon Corporation', 'https://www.mondragon-corporation.com/')],
    whyItMatters: 'Co-ops are a voluntary form, not a mandate to abolish investor-owned firms.',
    relatedClaimIds: ['profit-is-theft'],
    tags: ['cooperatives', 'workers'],
  },
  {
    id: 'finance-parasitic',
    topicId: 'profit-exploitation',
    title: 'Finance Is Parasitic on the Real Economy',
    socialistClaim: 'Banks add no value — pure extraction.',
    executiveSummary: 'Financial intermediation allocates capital to productive uses. Shallow capital markets correlate with slower growth.',
    evidenceBullets: ['King & Levine: finance-growth literature', 'Developing nations: shallow finance limits growth'],
    fallacies: ['zero-sum thinking'],
    sources: [src('Federal Reserve', 'https://www.federalreserve.gov/')],
    whyItMatters: 'Demonizing finance invites policy that starves Main Street of credit.',
    relatedClaimIds: ['profit-is-theft'],
    tags: ['finance', 'banks'],
  },
  {
    id: 'ussr-not-real-socialism',
    topicId: 'historical-socialism',
    title: "USSR Wasn't Real Socialism",
    socialistClaim: 'Every socialist failure was not real socialism.',
    executiveSummary: 'The USSR implemented state ownership, central planning, and one-party control. Outcomes: famine, gulags, stagnation, collapse.',
    evidenceBullets: ['Conquest: 20M+ deaths from famines/purges/Gulag', 'Soviet archival economic stagnation data'],
    fallacies: ['no true Scotsman'],
    sources: [src('Hoover Institution Archives', 'https://www.hoover.org/', 'primary'), src('Robert Conquest scholarship', 'https://www.hoover.org/research', 'academic')],
    whyItMatters: 'No-true-Scotsman prevents learning from the largest socialist experiment in history.',
    relatedClaimIds: ['china-famine', 'cambodia-ignored'],
    tags: ['ussr', 'socialism', 'history'],
  },
  {
    id: 'china-famine',
    topicId: 'historical-socialism',
    title: "Mao's China Was Misunderstood",
    socialistClaim: 'Mao-era famine is Western propaganda.',
    executiveSummary: 'Archival and demographic work documents catastrophic famine from collectivization (1958-1962). Dikötter estimates ~45 million deaths.',
    evidenceBullets: ['Dikötter: Mao\'s Great Famine archival evidence', 'Demographic reconstruction studies'],
    fallacies: ['historical revisionism'],
    sources: [src('Frank Dikötter research', 'https://www.hoover.org/', 'academic')],
    whyItMatters: 'Denying Mao-era catastrophe blocks honest comparison of institutions.',
    relatedClaimIds: ['ussr-not-real-socialism'],
    tags: ['china', 'mao', 'famine'],
  },
  {
    id: 'venezuela-sanctions',
    topicId: 'historical-socialism',
    title: 'Venezuela Failed Due to Sanctions',
    socialistClaim: 'Venezuela collapsed because of U.S. sanctions, not socialism.',
    executiveSummary: 'Economic free-fall followed expropriations, price controls, and money printing before major oil sanctions. Oil output collapsed under state management.',
    evidenceBullets: ['World Bank: ~75% GDP/capita decline 2013-2020', 'IMF hyperinflation data'],
    fallacies: ['post hoc', 'single-cause fallacy'],
    sources: [src('World Bank Venezuela', 'https://data.worldbank.org/country/venezuela'), src('IMF', 'https://www.imf.org/')],
    whyItMatters: 'Sanctions-blame avoids lessons on property rights and monetary discipline.',
    relatedClaimIds: ['cuba-poverty'],
    tags: ['venezuela', 'sanctions', 'socialism'],
  },
  {
    id: 'cuba-poverty',
    topicId: 'historical-socialism',
    title: 'Cuba Has Better Healthcare Than the U.S.',
    socialistClaim: 'Cuba proves socialism delivers superior outcomes.',
    executiveSummary: 'Official Cuban statistics lack independent audit. Mass emigration and dual-currency realities contradict paradise narratives.',
    evidenceBullets: ['Migration as revealed preference', 'Heritage: Cuba economic freedom score'],
    fallacies: ['cherry-picking'],
    sources: [src('Heritage Index Cuba', 'https://www.heritage.org/country/cuba'), src('Human Rights Watch Cuba', 'https://www.hrw.org/', 'primary')],
    whyItMatters: 'Romanticizing Cuba obscures lack of political and economic freedom.',
    relatedClaimIds: ['venezuela-sanctions'],
    tags: ['cuba', 'healthcare'],
  },
  {
    id: 'cambodia-ignored',
    topicId: 'historical-socialism',
    title: 'Khmer Rouge Was an Aberration',
    socialistClaim: 'Pol Pot does not count as socialism.',
    executiveSummary: 'Democratic Kampuchea abolished money and collectivized agriculture. Estimated 1.5-2 million deaths from execution, famine, and forced labor.',
    evidenceBullets: ['Documentation Center of Cambodia estimates', 'UN tribunal records'],
    fallacies: ['no true Scotsman'],
    sources: [src('Documentation Center of Cambodia', 'https://www.dccam.org/', 'primary')],
    whyItMatters: 'Radical egalitarian projects can produce radical horror.',
    relatedClaimIds: ['ussr-not-real-socialism'],
    tags: ['cambodia', 'khmer rouge'],
  },
  {
    id: 'nordic-socialist',
    topicId: 'nordic-democratic-socialism',
    title: 'Nordic Countries Are Socialist',
    socialistClaim: 'We should be like Sweden — democratic socialism works.',
    executiveSummary: 'Nordics are market economies with open trade and strong property rights. High taxes fund welfare, not collective ownership of production.',
    evidenceBullets: ['Heritage: Denmark/Sweden ranked mostly free', 'Fraser: Nordic business freedom scores'],
    fallacies: ['definitional sleight of hand'],
    sources: [src('Heritage Index', 'https://www.heritage.org/index/'), src('Fraser Institute', 'https://www.fraserinstitute.org/', 'think_tank')],
    whyItMatters: 'Mislabeling Nordics as socialist leads to wrong policy imports.',
    relatedClaimIds: ['nordic-capitalist', 'democratic-socialism-definition'],
    tags: ['nordic', 'sweden', 'democratic socialism'],
  },
  {
    id: 'nordic-capitalist',
    topicId: 'nordic-democratic-socialism',
    title: 'Nordics Succeeded Because of Socialism',
    socialistClaim: 'Nordic prosperity proves socialism works.',
    executiveSummary: 'Prosperity predates the modern welfare state. Post-1990 reforms liberalized markets after crisis.',
    evidenceBullets: ['Historical GDP/capita before welfare expansion', '1990s Swedish banking crisis reforms'],
    fallacies: ['post hoc'],
    sources: [src('World Bank historical data', 'https://data.worldbank.org/')],
    whyItMatters: 'Credit belongs to institutions and trade, not redistribution alone.',
    relatedClaimIds: ['nordic-socialist'],
    tags: ['nordic', 'prosperity'],
  },
  {
    id: 'democratic-socialism-definition',
    topicId: 'nordic-democratic-socialism',
    title: 'Democratic Socialism Is Just Welfare',
    socialistClaim: 'Democratic socialism is just Scandinavian welfare.',
    executiveSummary: 'Modern democratic socialists advocate worker ownership and nationalization beyond Nordic tax-and-transfer models.',
    evidenceBullets: ['DSA platform: public ownership goals', 'Nordic PMs rejecting socialist label'],
    fallacies: ['motte and bailey'],
    sources: [src('DSA About', 'https://www.dsausa.org/')],
    whyItMatters: 'Voters deserve clarity on what policies are actually proposed.',
    relatedClaimIds: ['nordic-socialist', 'socialism-democratic-better'],
    tags: ['democratic socialism', 'welfare'],
  },
  {
    id: 'socialism-democratic-better',
    topicId: 'nordic-democratic-socialism',
    title: 'Democratic Socialism Avoids Authoritarianism',
    socialistClaim: 'Democratic socialism cannot become authoritarian.',
    executiveSummary: 'Elected mandates enabled Chavez authoritarianism and Weimar-era central planning politics. Democracy needs constitutional limits.',
    evidenceBullets: ['Chavez electoral authoritarian trajectory', 'Hayek: democracy and unlimited majority'],
    fallacies: ['definitional dodge'],
    sources: [src('Freedom House Venezuela', 'https://freedomhouse.org/')],
    whyItMatters: 'Unlimited majorities can extinguish the liberties socialism claims to expand.',
    relatedClaimIds: ['ussr-not-real-socialism'],
    tags: ['democracy', 'authoritarianism'],
  },
  {
    id: 'economic-democracy',
    topicId: 'nordic-democratic-socialism',
    title: 'Economic Democracy Replaces Exploitation',
    socialistClaim: 'Workers voting on production ends exploitation.',
    executiveSummary: 'Votes over capital allocation recreate calculation and knowledge problems. Political majorities can expropriate minorities.',
    evidenceBullets: ['Mises: calculation problem for worker councils', 'Yugoslav self-management stagnation'],
    fallacies: ['category error'],
    sources: [src('Mises calculation problem', 'https://mises.org/', 'academic')],
    whyItMatters: 'Firm-level democracy without prices duplicates planning failures.',
    relatedClaimIds: ['calculation-impossible'],
    tags: ['economic democracy', 'cooperatives'],
  },
  {
    id: 'calculation-impossible',
    topicId: 'human-nature-incentives',
    title: 'Central Planning Works With Modern AI',
    socialistClaim: 'AI makes socialist planning feasible.',
    executiveSummary: 'Hayek\'s knowledge problem is not computing speed — prices aggregate tacit local knowledge no dataset captures.',
    evidenceBullets: ['Hayek: The Use of Knowledge in Society', 'Mises: Economic Calculation in the Socialist Commonwealth'],
    fallacies: ['technocratic fallacy'],
    sources: [src('Hayek', 'https://www.econlib.org/library/Essays/hykKnw.html', 'academic')],
    whyItMatters: 'Techno-utopian planning revives failed ideas with new buzzwords.',
    relatedClaimIds: ['incentives-matter', 'market-failures-require-socialism'],
    tags: ['calculation problem', 'hayek', 'planning'],
  },
  {
    id: 'incentives-matter',
    topicId: 'human-nature-incentives',
    title: 'People Work Hard Without Profit',
    socialistClaim: 'Humans will produce enthusiastically without material incentives.',
    executiveSummary: 'USSR, Mao, and Venezuela show incentive erosion, shortages, and corruption when property rights weaken.',
    evidenceBullets: ['Fraser: economic freedom and growth', 'Historical shortage economies'],
    fallacies: ['wishful thinking'],
    sources: [src('Fraser Institute', 'https://www.fraserinstitute.org/', 'think_tank')],
    whyItMatters: 'Ignoring incentives produces policy that sounds moral but harms the poor.',
    relatedClaimIds: ['calculation-impossible'],
    tags: ['incentives', 'human nature'],
  },
  {
    id: 'human-nature-altruism',
    topicId: 'human-nature-incentives',
    title: 'Humans Are Naturally Cooperative Not Competitive',
    socialistClaim: 'Markets impose unnatural greed.',
    executiveSummary: 'Markets channel self-interest through voluntary exchange. Cooperation requires institutions that align incentives.',
    evidenceBullets: ['Smith: coordination via markets', 'Bastiat: legal plunder distinction'],
    fallacies: ['false dichotomy'],
    sources: [src('Adam Smith Institute', 'https://www.adamsmith.org/', 'think_tank')],
    whyItMatters: 'Markets are cooperation at scale, not greed unleashed.',
    relatedClaimIds: ['incentives-matter'],
    tags: ['human nature', 'cooperation'],
  },
  {
    id: 'market-failures-require-socialism',
    topicId: 'human-nature-incentives',
    title: 'Market Failures Require Socialism',
    socialistClaim: 'Externalities prove markets fail — only socialism fixes them.',
    executiveSummary: 'Pigouvian taxes, Coasean property rights, and permit markets address externalities without abolishing ownership.',
    evidenceBullets: ['Coase Theorem applications', 'Cap-and-trade programs'],
    fallacies: ['false dichotomy'],
    sources: [src('EPA Cap and Trade', 'https://www.epa.gov/')],
    whyItMatters: 'Externalities justify correction, not collectivization.',
    relatedClaimIds: ['green-new-deal-growth'],
    tags: ['market failure', 'externalities'],
  },
  {
    id: 'minimum-wage-no-harm',
    topicId: 'government-intervention',
    title: "Minimum Wage Raises Don't Cost Jobs",
    socialistClaim: 'Minimum wage increases help workers with no downside.',
    executiveSummary: 'When wages exceed marginal product for some workers, hours and employment compress — especially for teens and low-skill entrants.',
    evidenceBullets: ['Jardim et al. Seattle study', 'CBO federal $15 minimum wage analysis'],
    fallacies: ['seen vs unseen'],
    sources: [src('NBER Working Paper 25432', 'https://www.nber.org/', 'academic'), src('CBO', 'https://www.cbo.gov/')],
    whyItMatters: 'Well-intentioned wage floors can exclude the most vulnerable from first rungs.',
    relatedClaimIds: ['minimum-wage-entry'],
    tags: ['minimum wage', 'jobs'],
  },
  {
    id: 'minimum-wage-entry',
    topicId: 'government-intervention',
    title: 'Minimum Wage Is Best Anti-Poverty Tool',
    socialistClaim: 'Raising minimum wage is the best way to fight poverty.',
    executiveSummary: 'Most minimum-wage earners are not household breadwinners in poverty. EITC targets poverty more precisely.',
    evidenceBullets: ['BLS minimum wage earner demographics', 'CBO EITC comparison'],
    fallacies: ['category error'],
    sources: [src('BLS', 'https://www.bls.gov/')],
    whyItMatters: 'Wrong tool wastes political capital that could fund EITC expansion.',
    relatedClaimIds: ['minimum-wage-no-harm'],
    tags: ['minimum wage', 'poverty', 'eitc'],
  },
  {
    id: 'healthcare-right',
    topicId: 'government-intervention',
    title: 'Healthcare Is a Right — Single Payer Now',
    socialistClaim: 'Healthcare is a human right requiring single-payer.',
    executiveSummary: 'Rights as claims on others\' labor imply coercion. Single-payer systems face wait times and rationing.',
    evidenceBullets: ['OECD wait time comparisons', 'Fraser health freedom indices'],
    fallacies: ['rights inflation'],
    sources: [src('OECD Health', 'https://www.oecd.org/health/')],
    whyItMatters: 'Rights language obscures tradeoffs between access, quality, and fiscal sustainability.',
    relatedClaimIds: ['healthcare-cost'],
    tags: ['healthcare', 'single payer'],
  },
  {
    id: 'healthcare-cost',
    topicId: 'government-intervention',
    title: "Free Markets Can't Provide Healthcare",
    socialistClaim: 'Only government can control healthcare costs.',
    executiveSummary: 'Medical cost inflation accelerated after Medicare/Medicaid expansion — classic third-party payer problem.',
    evidenceBullets: ['Medical CPI vs general CPI divergence', 'Third-party payment literature'],
    fallacies: ['post hoc'],
    sources: [src('BLS Medical CPI', 'https://www.bls.gov/cpi/')],
    whyItMatters: 'More third-party payment may worsen the cost disease it claims to cure.',
    relatedClaimIds: ['healthcare-right'],
    tags: ['healthcare', 'costs'],
  },
  {
    id: 'ubi-solves-all',
    topicId: 'government-intervention',
    title: 'UBI Will End Poverty',
    socialistClaim: 'Universal Basic Income eliminates poverty and job fears.',
    executiveSummary: 'UBI faces enormous fiscal cost and mixed labor supply evidence from pilots.',
    evidenceBullets: ['CBO UBI cost estimates', 'Finland UBI trial labor results'],
    fallacies: ['magic bullet thinking'],
    sources: [src('CBO', 'https://www.cbo.gov/')],
    whyItMatters: 'Fiscal reality limits UBI scale without damaging growth.',
    relatedClaimIds: ['minimum-wage-no-harm'],
    tags: ['ubi', 'poverty'],
  },
  {
    id: 'rent-control-helps',
    topicId: 'government-intervention',
    title: 'Rent Control Protects the Poor',
    socialistClaim: 'Rent control keeps housing affordable.',
    executiveSummary: 'Rent control reduces supply and maintenance. Stanford found SF rent control raised citywide rents 5-10%.',
    evidenceBullets: ['Diamond et al. Stanford SF study', 'Gyourko & Linneman research'],
    fallacies: ['seen vs unseen'],
    sources: [src('Stanford Economics', 'https://www.stanford.edu/', 'academic')],
    whyItMatters: 'Rent control helps incumbents at the expense of newcomers and builders.',
    relatedClaimIds: ['housing-late-capitalism'],
    tags: ['rent control', 'housing'],
  },
  {
    id: 'green-new-deal-growth',
    topicId: 'government-intervention',
    title: 'Green New Deal Creates Prosperity',
    socialistClaim: 'Massive state green investment will grow the economy.',
    executiveSummary: 'Central energy allocation risks malinvestment. Market carbon pricing plus innovation outperforms command-and-control.',
    evidenceBullets: ['Spanish green jobs study', 'IEA innovation data'],
    fallacies: ['broken window fallacy'],
    sources: [src('IEA', 'https://www.iea.org/')],
    whyItMatters: 'Climate policy should not repeat industrial planning failures.',
    relatedClaimIds: ['climate-capitalism-failed'],
    tags: ['green new deal', 'climate'],
  },
  {
    id: 'education-free',
    topicId: 'government-intervention',
    title: 'College Should Be Free',
    socialistClaim: 'Student debt proves capitalism failed education.',
    executiveSummary: 'Tuition subsidies inflate administrative bloat. Market alternatives address access without zero price signals.',
    evidenceBullets: ['Federal aid correlation with tuition inflation', 'BLS college premium data'],
    fallacies: ['price signal denial'],
    sources: [src('Federal Reserve education finance', 'https://www.federalreserve.gov/')],
    whyItMatters: 'Free tuition without reform subsidizes bureaucracy, not learning.',
    relatedClaimIds: ['healthcare-right'],
    tags: ['education', 'student debt'],
  },
  {
    id: 'capitalism-poverty',
    topicId: 'global-poverty-capitalism',
    title: 'Capitalism Created Global Poverty',
    socialistClaim: 'Colonialism and capitalism impoverished the Global South.',
    executiveSummary: 'Extreme poverty fell fastest where countries integrated with global markets — China, India, Vietnam.',
    evidenceBullets: ['World Bank 1990-2022 poverty decline', 'China post-1978 GDP/capita growth'],
    fallacies: ['historical cherry-picking'],
    sources: [src('World Bank', 'https://www.worldbank.org/')],
    whyItMatters: 'Anti-market narratives ignore the greatest poverty reduction in history.',
    relatedClaimIds: ['colonialism-blame', 'africa-exploited'],
    tags: ['poverty', 'global south', 'capitalism'],
  },
  {
    id: 'colonialism-blame',
    topicId: 'global-poverty-capitalism',
    title: 'All Poverty Is Colonial Legacy',
    socialistClaim: 'Modern poverty is purely colonial legacy.',
    executiveSummary: 'Singapore, Botswana, and South Korea outperformed after institutional and market reforms.',
    evidenceBullets: ['Acemoglu & Robinson institutions thesis', 'Heritage growth correlations'],
    fallacies: ['single-cause fallacy'],
    sources: [src('MIT Daron Acemoglu', 'https://economics.mit.edu/', 'academic')],
    whyItMatters: 'Institutions today matter more than history alone for policy.',
    relatedClaimIds: ['capitalism-poverty'],
    tags: ['colonialism', 'development'],
  },
  {
    id: 'africa-exploited',
    topicId: 'global-poverty-capitalism',
    title: 'Africa Is Poor Because of Western Exploitation',
    socialistClaim: 'Africa remains poor because the West exploits it.',
    executiveSummary: 'Internal institutions, conflict, and policy dominate. African nations improving economic freedom grow faster.',
    evidenceBullets: ['Fraser Africa trends', 'World Bank governance indicators'],
    fallacies: ['zero-sum thinking'],
    sources: [src('World Bank Africa', 'https://www.worldbank.org/en/region/afr')],
    whyItMatters: 'Victim narratives excuse corrupt governance that hurts Africans most.',
    relatedClaimIds: ['capitalism-poverty'],
    tags: ['africa', 'exploitation'],
  },
  {
    id: 'founding-collectivist',
    topicId: 'founding-principles',
    title: 'Founders Supported Collectivism',
    socialistClaim: 'The Founders would support modern democratic socialism.',
    executiveSummary: 'Madison and Jefferson warned against consolidated power and factional redistribution. Constitution protects property and liberty.',
    evidenceBullets: ['Federalist 10 on factions', 'Locke on property rights'],
    fallacies: ['historical revisionism'],
    sources: [src('Founders Online', 'https://founders.archives.gov/', 'primary')],
    whyItMatters: 'Founding literacy is essential to constitutional debate.',
    relatedClaimIds: ['constitution-limits', 'natural-rights'],
    tags: ['founders', 'constitution'],
  },
  {
    id: 'constitution-limits',
    topicId: 'founding-principles',
    title: 'Constitution Mandates Welfare Expansion',
    socialistClaim: 'The Constitution requires modern welfare programs.',
    executiveSummary: 'Constitution enumerates limited powers. Redistribution is political choice, not constitutional mandate.',
    evidenceBullets: ['Article I Section 8 enumeration', 'Federalist 45 limited federal role'],
    fallacies: ['wishful interpretation'],
    sources: [src('Constitution.gov', 'https://constitution.congress.gov/', 'primary')],
    whyItMatters: 'Conflating politics with constitutional duty erodes civic education.',
    relatedClaimIds: ['founding-collectivist'],
    tags: ['constitution', 'welfare'],
  },
  {
    id: 'natural-rights',
    topicId: 'founding-principles',
    title: 'Rights Come From Government',
    socialistClaim: 'Rights are whatever society democratically grants.',
    executiveSummary: 'Founders held rights pre-exist government. Government exists to secure them.',
    evidenceBullets: ['Declaration: unalienable rights', 'Locke Second Treatise'],
    fallacies: ['positivist confusion'],
    sources: [src('National Archives Declaration', 'https://www.archives.gov/founding-docs/declaration', 'primary')],
    whyItMatters: 'Contingent rights are rights no minority can trust.',
    relatedClaimIds: ['constitution-limits'],
    tags: ['rights', 'natural law'],
  },
  {
    id: 'open-borders-socialist',
    topicId: 'founding-principles',
    title: 'Borders Are Capitalist Oppression',
    socialistClaim: 'Open borders are required for justice.',
    executiveSummary: 'Sovereignty enables rule of law and public goods. Unrestricted migration strains fiscal capacity — Bastiat seen/unseen applies.',
    evidenceBullets: ['Fiscal impact migration studies', 'Bastiat unseen consequences'],
    fallacies: ['internally inconsistent'],
    sources: [src('Cato Institute immigration', 'https://www.cato.org/', 'think_tank')],
    whyItMatters: 'Open borders advocacy conflicts with large welfare states.',
    relatedClaimIds: ['constitution-limits'],
    tags: ['borders', 'immigration'],
  },
  {
    id: 'free-speech-fascism',
    topicId: 'free-speech-socialist-regimes',
    title: 'Socialist Regimes Support Free Speech',
    socialistClaim: 'Real socialism empowers the people\'s voice.',
    executiveSummary: 'USSR, China, Cuba, and Venezuela criminalized or crushed dissent systematically.',
    evidenceBullets: ['HRW country reports', 'Soviet Criminal Code Article 58'],
    fallacies: ['Orwellian reversal'],
    sources: [src('Human Rights Watch', 'https://www.hrw.org/')],
    whyItMatters: 'Free speech is the first casualty when state power owns the public square.',
    relatedClaimIds: ['censorship-private', 'ussr-not-real-socialism'],
    tags: ['free speech', 'censorship'],
  },
  {
    id: 'censorship-private',
    topicId: 'free-speech-socialist-regimes',
    title: 'Private Censorship Is Worse Than State',
    socialistClaim: 'Corporate moderation is fascism worse than socialist states.',
    executiveSummary: 'State censorship uses force and imprisonment. Private moderation is contractual — different category.',
    evidenceBullets: ['First Amendment state action doctrine', 'FIRE educational resources'],
    fallacies: ['false equivalence'],
    sources: [src('FIRE', 'https://www.thefire.org/', 'think_tank')],
    whyItMatters: 'Conflating categories obscures socialist regimes\' dissent record.',
    relatedClaimIds: ['free-speech-fascism'],
    tags: ['censorship', 'free speech'],
  },
  {
    id: 'late-stage-capitalism',
    topicId: 'late-stage-capitalism',
    title: 'Late-Stage Capitalism Is Collapsing',
    socialistClaim: 'We are in late-stage capitalism — collapse is imminent.',
    executiveSummary: 'No terminal stage exists in market economies. GDP, life expectancy, and technology continue upward in market nations.',
    evidenceBullets: ['BEA real GDP growth', 'Our World in Data life expectancy'],
    fallacies: ['pseudo-Marxist teleology'],
    sources: [src('BEA', 'https://www.bea.gov/')],
    whyItMatters: 'Apocalyptic framing replaces measurable policy debate.',
    relatedClaimIds: ['wealth-inequality-broken', 'monopoly-inevitable'],
    tags: ['late stage capitalism', 'collapse'],
  },
  {
    id: 'monopoly-inevitable',
    topicId: 'late-stage-capitalism',
    title: 'Capitalism Inevitably Creates Monopolies',
    socialistClaim: 'Markets always monopolize without socialism.',
    executiveSummary: 'Entry, disruption, and antitrust limit durable monopoly. State monopolies face no entry discipline.',
    evidenceBullets: ['Fortune 500 turnover', 'DOJ antitrust enforcement'],
    fallacies: ['static analysis'],
    sources: [src('DOJ Antitrust Division', 'https://www.justice.gov/atr')],
    whyItMatters: 'Competition policy beats nationalization for consumer welfare.',
    relatedClaimIds: ['profit-is-theft'],
    tags: ['monopoly', 'antitrust'],
  },
  {
    id: 'climate-capitalism-failed',
    topicId: 'late-stage-capitalism',
    title: 'Capitalism Destroyed the Climate',
    socialistClaim: 'Only socialism can solve climate change.',
    executiveSummary: 'Economic freedom correlates with environmental outcomes via innovation. USSR was a notorious polluter.',
    evidenceBullets: ['Fraser environmental indices', 'Soviet environmental disaster record'],
    fallacies: ['single-tool fallacy'],
    sources: [src('Fraser Institute', 'https://www.fraserinstitute.org/', 'think_tank')],
    whyItMatters: 'Central planning is not inherently green — history shows the opposite.',
    relatedClaimIds: ['green-new-deal-growth'],
    tags: ['climate', 'environment'],
  },
  {
    id: 'housing-late-capitalism',
    topicId: 'late-stage-capitalism',
    title: 'Housing Crisis Proves Capitalism Failed',
    socialistClaim: 'Housing unaffordability is late-stage capitalism.',
    executiveSummary: 'Zoning and land-use regulation constrain supply. Government restrictions dominate coastal affordability crises.',
    evidenceBullets: ['Glaeser zoning research', 'Freddie Mac supply deficit studies'],
    fallacies: ['omitted variable'],
    sources: [src('Freddie Mac', 'https://www.freddiemac.com/')],
    whyItMatters: 'Deregulating supply beats price controls for housing affordability.',
    relatedClaimIds: ['rent-control-helps'],
    tags: ['housing', 'zoning'],
  },
  {
    id: 'automation-unemployment',
    topicId: 'late-stage-capitalism',
    title: 'Automation Causes Permanent Unemployment',
    socialistClaim: 'Robots will leave everyone unemployed under capitalism.',
    executiveSummary: 'Technology displaces tasks but raises productivity and creates new work. Lump of labor is a fallacy.',
    evidenceBullets: ['BLS occupational growth categories', 'Historical automation employment transitions'],
    fallacies: ['lump of labor fallacy'],
    sources: [src('BLS Employment Projections', 'https://www.bls.gov/emp/')],
    whyItMatters: 'Automation panic justifies Luddite policy that slows progress.',
    relatedClaimIds: ['minimum-wage-no-harm'],
    tags: ['automation', 'jobs', 'ai'],
  },
];

const enriched = claims.map((c) => ({
  ...c,
  claimQuote: c.claimQuote ?? null,
  chartData: c.chartData ?? null,
  updatedAt: '2026-07-04',
  searchText: [c.title, c.socialistClaim, c.executiveSummary, ...(c.tags || [])].join(' '),
}));

const output = { version: '1.0.0', updatedAt: '2026-07-04', claims: enriched };
const outPath = join(__dirname, '..', 'assets', 'data', 'claims_seed.json');
writeFileSync(outPath, JSON.stringify(output, null, 2), 'utf8');
console.log(`Generated ${enriched.length} claims -> ${outPath}`);