# Generates assets/data/claims_seed.json with 45 sourced claim/counter pairs.
$claims = @()

function New-Claim($id, $topicId, $title, $claim, $summary, $bullets, $fallacies, $sources, $why, $related, $tags) {
    return @{
        id = $id
        topicId = $topicId
        title = $title
        socialistClaim = $claim
        claimQuote = $null
        executiveSummary = $summary
        evidenceBullets = $bullets
        chartData = $null
        fallacies = $fallacies
        sources = $sources
        whyItMatters = $why
        relatedClaimIds = $related
        tags = $tags
        updatedAt = "2026-07-04"
        searchText = "$title $claim $summary $($tags -join ' ')"
    }
}

$src = {
    param($t, $u, $type)
    @{ title = $t; url = $u; doi = $null; type = $type }
}

# 45 claims across all topics
$claims += New-Claim "wealth-inequality-broken" "wealth-inequality-mobility" "Wealth Inequality Proves Capitalism Is Broken" `
    "Rising wealth inequality proves capitalism is fundamentally broken and immoral." `
    "Relative inequality metrics tell us nothing about absolute living standards without context. The U.S. bottom quintile's real consumption has risen dramatically since 1960 while global extreme poverty collapsed under market integration. Inequality can rise while everyone gets richer — the relevant question is whether the poor have exit options, property rights, and upward mobility." `
    @("CBO: bottom quintile real consumption +60% (1960-2019)", "World Bank: extreme poverty 36% to ~8.5% (1990-2022)", "Chetty: ~7.5% of bottom-quintile children reach top quintile") `
    @("zero-sum thinking", "confusing relative with absolute") `
    @(&$src "CBO Distribution of Household Income" "https://www.cbo.gov/topics/income-distribution" "government") `
    "America's debate confuses envy metrics with outcomes. Policy should target mobility and poverty, not Gini worship." `
    @("consumption-vs-income") @("inequality", "wealth", "gini", "mobility")

$claims += New-Claim "consumption-vs-income" "wealth-inequality-mobility" "Income Inequality Equals Material Deprivation" `
    "The poor are getting poorer because the income gap is widening." `
    "Income snapshots ignore taxes, transfers, household size, and lifecycle effects. Consumption inequality is far narrower than income inequality in the U.S., and material goods once reserved for the rich (smartphones, AC, cars) are ubiquitous at lower income levels." `
    @("Meyer & Sullivan: consumption inequality narrower than income inequality", "BLS Consumer Expenditure Survey shows broad access to durables", "Transfer payments materially raise bottom-quintile resources") `
    @("static snapshot fallacy", "omitted variable bias") `
    @(&$src "BLS Consumer Expenditure Survey" "https://www.bls.gov/cex/" "government") `
    "Political rhetoric uses pre-tax income to manufacture a crisis that consumption data does not support." `
    @("wealth-inequality-broken") @("consumption", "income", "poverty")

# Add 43 more via compact definitions
$more = @(
    @("gini-misused","wealth-inequality-mobility","The Gini Coefficient Proves Unfairness","America's Gini coefficient proves our system is unfair.","Gini measures dispersion, not injustice. Mixed economies with heavy transfer states can have similar Ginis while differing vastly in growth and mobility.","@('Heritage: economic freedom correlates with prosperity','Gini ignores government transfers and household composition')","@('metric fixation','ecological fallacy')","wealth-inequality-broken"),
    @("mobility-dead","wealth-inequality-mobility","The American Dream Is Dead","Poor Americans are stuck — there is no upward mobility.","Absolute mobility has softened, but relative mobility exists and responds to local policy: family structure, school quality, and economic freedom.","@('Chetty et al. county-level mobility variation','Fraser: freer economies grow faster')","@('anecdotal generalization')","wealth-inequality-broken"),
    @("profit-is-theft","profit-exploitation","Profit Is Theft From Workers","Profit is extracted surplus value stolen from workers.","Profit compensates uncertainty, capital coordination, and innovation. In competitive markets, excess profits attract entry and compress margins. Workers voluntarily exchange labor for wages; surplus value theory cannot explain prices without circular reasoning.","@('Mises: prices coordinate dispersed knowledge','Competitive markets compress abnormal profits')","@('labor theory of value','zero-sum thinking')","exploitation-marx"),
    @("exploitation-marx","profit-exploitation","Workers Are Exploited Under Capitalism","Capitalists exploit workers by paying less than value created.","Value is subjective, not embedded labor-hours. Real compensation tracks productivity over time where markets function. Exploitation claims ignore consumer surplus, voluntary exchange, and the role of capital in raising marginal product.","@('BEA: labor productivity and compensation correlation','BLS productivity data')","@('labor theory of value','appeal to envy')","profit-is-theft"),
    @("rich-get-richer-poor-poorer","profit-exploitation","The Rich Get Richer, Poor Get Poorer","Under capitalism the rich always get richer while the poor get poorer.","Both groups can rise simultaneously. Global and U.S. data show rising real incomes at the bottom over decades, not universal immiseration.","@('Census real median household income records','World Bank poverty decline')","@('zero-sum thinking')","wealth-inequality-broken"),
    @("ussr-not-real-socialism","historical-socialism","USSR Wasn't Real Socialism","Every socialist failure wasn't real socialism.","The USSR implemented state ownership of means of production, central planning, and one-party control — the textbook definition. Outcomes: famine, gulags, stagnation, collapse.","@('Conquest: 20M+ deaths from famines/purges/Gulag','Archival food procurement data')","@('no true Scotsman')","china-famine"),
    @("china-famine","historical-socialism","Mao's China Was Misunderstood","Mao's collectivization was exaggerated by Western propaganda.","Primary records and demographic analysis document catastrophic famine from collectivization (1958-1962). Dikötter's archival work estimates ~45 million deaths.","@('Dikötter: Mao''s Great Famine','Demographic reconstruction studies')","@('historical revisionism')","ussr-not-real-socialism"),
    @("venezuela-sanctions","historical-socialism","Venezuela Failed Due to Sanctions","Venezuela's collapse was caused by U.S. sanctions, not socialism.","Venezuela's economic free-fall preceded major oil sanctions and followed expropriations, price controls, and money printing. Oil production collapsed under state management.","@('World Bank: ~75% GDP/capita decline 2013-2020','IMF hyperinflation data')","@('post hoc','single-cause fallacy')","cuba-poverty"),
    @("cuba-poverty","historical-socialism","Cuba Has Better Healthcare Than the U.S.","Cuba proves socialism delivers superior outcomes.","Official Cuban statistics are not independently auditable. Emigration patterns (raft exodus) and dual-currency realities tell a different story. Relative to region, Cuba underperformed market reformers.","@('Heritage economic freedom rankings','Migration as revealed preference')","@('cherry-picking','appeal to authority')","venezuela-sanctions"),
    @("cambodia-ignored","historical-socialism","Khmer Rouge Was an Aberration","Pol Pot doesn't count as socialism.","Democratic Kampuchea abolished money, collectivized agriculture, and murdered class enemies — a radical socialist experiment. ~1.5-2 million deaths from execution, famine, and forced labor.","@('Documentation Center of Cambodia estimates','UN tribunal records')","@('no true Scotsman')","ussr-not-real-socialism"),
    @("nordic-socialist","nordic-democratic-socialism","Nordic Countries Are Socialist","We should be like Sweden — democratic socialism works.","Nordics are market economies with open trade, strong property rights, and business freedom; they score high on Heritage/Fraser indices. High taxes fund welfare states, not collective ownership of production.","@('Heritage: Denmark/Sweden in ''mostly free''','Fraser: Nordic business freedom scores')","@('definitional sleight of hand')","nordic-capitalist"),
    @("nordic-capitalist","nordic-democratic-socialism","Nordics Succeeded Because of Socialism","Nordic prosperity proves socialism works.","Nordic prosperity predates the modern welfare state, built on trade, rule of law, and Lutheran work culture. Post-1970 reforms liberalized markets (e.g., Sweden's banking crisis response).","@('Historical GDP/capita before welfare expansion','1990s Nordic market reforms')","@('post hoc')","nordic-socialist"),
    @("democratic-socialism-definition","nordic-democratic-socialism","Democratic Socialism Is Just Welfare","Democratic socialism is just Scandinavian welfare — nothing radical.","Modern democratic socialists advocate worker ownership, sector nationalization, and deep price controls — beyond Nordic tax-and-transfer models. Words matter in policy design.","@('DSA platform: worker cooperatives and public ownership','Nordic PMs rejecting ''socialist'' label')","@('motte and bailey')","nordic-socialist"),
    @("calculation-impossible","human-nature-incentives","Central Planning Can Work With Computers","Modern AI makes socialist planning feasible.","Hayek's knowledge problem is not a computing-speed issue — prices aggregate tacit, local, subjective knowledge no central dataset captures. Soviet reformers conceded this before collapse.","@('Hayek: The Use of Knowledge in Society','Mises: Economic Calculation in the Socialist Commonwealth')","@('technocratic fallacy')","incentives-matter"),
    @("incentives-matter","human-nature-incentives","People Will Work Hard Without Profit","Humans will produce enthusiastically without material incentives.","Repeated experiments (USSR, Mao, Venezuela) show incentive erosion, shortages, and corruption when property rights weaken.","@('Fraser: economic freedom and growth correlation','Historical shortage economies')","@('wishful thinking')","calculation-impossible"),
    @("human-nature-altruism","human-nature-incentives","Humans Are Naturally Cooperative Not Competitive","Markets impose unnatural greed.","Humans cooperate within institutions that align self-interest with social benefit. Markets channel self-interest via voluntary exchange; coercion destroys feedback loops.","@('Smith: invisible hand as coordination','Bastiat: The Law on legal plunder')","@('false dichotomy')","incentives-matter"),
    @("minimum-wage-no-harm","government-intervention","Minimum Wage Raises Don't Cost Jobs","Minimum wage increases help workers with no downside.","When wages are set above marginal product for some workers, hours and employment compress — especially for teens and low-skill entrants.","@('Jardim et al. Seattle study: hours fell','CBO: $15 federal minimum wage employment effects')","@('seen vs unseen')","minimum-wage-entry"),
    @("minimum-wage-entry","government-intervention","Minimum Wage Helps Entry-Level Workers","Raising the minimum wage is the best anti-poverty tool.","Most minimum-wage earners are not household breadwinners in poverty; many are second earners or young workers. EITC targets poverty more precisely.","@('BLS minimum wage earner demographics','CBO EITC vs minimum wage comparison')","@('category error')","minimum-wage-no-harm"),
    @("healthcare-right","government-intervention","Healthcare Is a Right — Single Payer Now","Healthcare is a human right requiring single-payer socialism.","Rights as claims on others' labor create coercion. Countries with single-payer face wait times, rationing, and tax burdens; market hybrids (Switzerland) outperform on access metrics.","@('Fraser health freedom indices','OECD wait time comparisons')","@('rights inflation')","healthcare-cost"),
    @("healthcare-cost","government-intervention","Free Markets Can't Provide Healthcare","Only government can control healthcare costs.","Pre-intervention history shows medical cost inflation accelerated after Medicare/Medicaid expansion and third-party payment — classic third-party payer problem.","@('Historical medical CPI vs general CPI','Baumol cost disease literature')","@('post hoc')","healthcare-right"),
    @("ubi-solves-all","government-intervention","UBI Will End Poverty","Universal Basic Income will eliminate poverty and job loss fears.","UBI faces enormous fiscal cost, disincentive effects at margin, and inflation pass-through unless paired with spending cuts. Pilot programs show mixed labor supply responses.","@('CBO UBI cost estimates','Finland UBI trial labor results')","@('magic bullet thinking')","minimum-wage-no-harm"),
    @("rent-control-helps","government-intervention","Rent Control Protects the Poor","Rent control keeps housing affordable for working families.","Rent control reduces supply, degrades maintenance, and benefits incumbent tenants over newcomers — Stanford study found 5-10% citywide rent increase from SF rent control.","@('Diamond et al. Stanford SF study','Gyourko & Linneman classic research')","@('seen vs unseen')","minimum-wage-no-harm"),
    @("green-new-deal-growth","government-intervention","Green New Deal Creates Prosperity","Massive state green investment will grow the economy.","Central allocation of energy infrastructure risks Solyndra-scale malinvestment. Market pricing of carbon + innovation outperforms command-and-control.","@('Spanish green jobs study: 2.2 jobs destroyed per created','IEA market innovation data')","@('broken window fallacy')","calculation-impossible"),
    @("education-free","government-intervention","College Should Be Free","Student debt proves capitalism failed education.","Tuition subsidies inflate administrative bloat and credential inflation. Income-share and market competition (e.g., trade schools, online) address access better than price ceilings at zero.","@('Federal student aid correlation with tuition inflation','BLS college premium data')","@('price signal denial')","healthcare-right"),
    @("capitalism-poverty","global-poverty-capitalism","Capitalism Created Global Poverty","Colonialism and capitalism impoverished the Global South.","Extreme poverty fell fastest where countries integrated with global markets (China post-1978, India post-1991, Vietnam). Absolute living standards rose, not fell.","@('World Bank: 1990-2022 poverty decline','China WTO integration GDP/capita')","@('historical cherry-picking')","wealth-inequality-broken"),
    @("colonialism-blame","global-poverty-capitalism","All Development Problems Are Colonial Legacy","Modern poverty is purely colonial legacy.","Many former colonies outperformed after market reforms (Singapore, Botswana, South Korea). Institutions — property rights, rule of law — predict growth more than colonial history alone.","@('Acemoglu & Robinson: institutions thesis','Heritage/Fraser growth correlations')","@('single-cause fallacy')","capitalism-poverty"),
    @("africa-exploited","global-poverty-capitalism","Africa Is Poor Because of Western Exploitation","Africa remains poor because the West exploits it.","Internal institutions, conflict, and policy choices dominate. African nations with economic freedom improvements show faster growth.","@('Fraser Africa sub-index trends','World Bank governance indicators')","@('zero-sum thinking')","capitalism-poverty"),
    @("founding-collectivist","founding-principles","Founders Supported Collectivism","The Founders would support modern democratic socialism.","Madison, Jefferson, and Adams warned against consolidated power and redistribution by faction. The Constitution limits government to protect property and liberty.","@('Federalist 10: faction control','Locke: property as extension of self-ownership')","@('historical revisionism')","constitution-limits"),
    @("constitution-limits","founding-principles","Constitution Is a Living Document for Social Justice","The Constitution mandates modern welfare expansion.","The Constitution enumerates limited powers. Redistribution programs require democratic politics, not constitutional mandate — conflating the two erodes constitutional literacy.","@('Article I Section 8 enumeration','Federalist 45: limited federal role')","@('wishful interpretation')","founding-collectivist"),
    @("natural-rights","founding-principles","Rights Come From Government","Rights are whatever society democratically grants.","Founders held rights pre-exist government. Government exists to secure them — reversing this makes rights contingent on majority whim.","@('Declaration of Independence: unalienable rights','Locke Second Treatise')","@('positivist confusion')","constitution-limits"),
    @("free-speech-fascism","free-speech-socialist-regimes","Socialist Regimes Support Free Speech","Real socialism empowers the people's voice.","Every major socialist state criminalized dissent: USSR (Gulag for anti-Soviet agitation), China (Tiananmen, Great Firewall), Cuba (political prisoners), Venezuela (media shutdowns).","@('Human Rights Watch country reports','Soviet Criminal Code Article 58')","@('Orwellian reversal')","ussr-not-real-socialism"),
    @("censorship-private","free-speech-socialist-regimes","Private Platform Censorship Is Fascism","Only socialist states censor — corporations are worse.","State censorship is backed by force and imprisonment; private moderation is contractual. Conflating them obscures the socialist track record on dissent.","@('State vs private actor legal distinction','FIRE First Amendment scope')","@('false equivalence')","free-speech-fascism"),
    @("late-stage-capitalism","late-stage-capitalism","Late-Stage Capitalism Is Collapsing","We are in late-stage capitalism — collapse is imminent.","There is no terminal 'stage' in market economies. Real GDP, life expectancy, and technology adoption continue upward in market-oriented nations.","@('BEA real GDP growth','Our World in Data life expectancy')","@('pseudo-Marxist teleology')","wealth-inequality-broken"),
    @("monopoly-inevitable","late-stage-capitalism","Capitalism Inevitably Creates Monopolies","Markets always monopolize without socialism.","Competitive entry, technology disruption, and antitrust where needed limit durable monopoly. Socialist monopolies (state enterprises) face no entry discipline.","@('DOJ antitrust enforcement history','Tech sector churn: Fortune 500 turnover')","@('static analysis')","profit-is-theft"),
    @("climate-capitalism-failed","late-stage-capitalism","Capitalism Destroyed the Climate","Only socialism can solve climate change.","Economic freedom correlates with environmental outcomes at income levels via innovation. Command economies (USSR) were notorious polluters.","@('Fraser environmental indices','Soviet environmental disaster record')","@('single-tool fallacy')","green-new-deal-growth"),
    @("housing-late-capitalism","late-stage-capitalism","Housing Crisis Proves Capitalism Failed","Housing unaffordability is late-stage capitalism.","Zoning, land-use regulation, and monetary policy dominate housing costs — government restrictions constrain supply.","@('Glaeser: zoning and housing costs','Freddie Mac housing supply deficit studies')","@('omitted variable')","rent-control-helps"),
    @("worker-coops-superior","profit-exploitation","Worker Cooperatives Prove Socialism Works","Co-ops outperform capitalist firms.","Co-ops thrive in niches but face capital-raising and scale constraints. They coexist in markets — proof of market pluralism, not socialism.","@('Mondragon case study limitations','VC-backed innovation scale advantages')","@('hasty generalization')","profit-is-theft"),
    @("finance-parasitic","profit-exploitation","Finance Is Parasitic on the Real Economy","Banks and finance add no value — pure extraction.","Financial intermediation allocates capital to productive uses. Without it, growth and innovation stall — see developing nations with shallow capital markets.","@('Goldsmith-McFadden financial depth and growth','King & Levine finance-growth literature')","@('zero-sum thinking')","profit-is-theft"),
    @("automation-unemployment","late-stage-capitalism","Automation Will Cause Permanent Unemployment","Robots will leave everyone unemployed under capitalism.","Historical technology waves displaced tasks but raised productivity and new jobs. Unemployment tracks policy shocks more than automation.","@('BLS occupational growth categories','Historical loom/automobile employment transitions')","@('lump of labor fallacy')","minimum-wage-no-harm"),
    @("billionaires-shouldnt-exist","wealth-inequality-mobility","Billionaires Shouldn't Exist","No one should have a billion dollars while others starve.","Wealth concentration reflects created value at scale. Taxing or capping wealth without growth tradeoffs risks capital flight and innovation loss. Poverty is addressed by growth, not wealth caps.","@('World Bank poverty vs billionaire wealth timing','Tax Foundation wealth tax revenue estimates')","@('appeal to envy','zero-sum thinking')","wealth-inequality-broken"),
    @("socialism-democratic-better","nordic-democratic-socialism","Democratic Socialism Is Different From Authoritarian","Democratic socialism avoids authoritarianism by definition.","Democratic mandates enabled Nazi-era central planning rhetoric and Chavez's elected authoritarianism. Democracy without constitutional limits enables tyranny of the majority.","@('Chavez electoral authoritarianism trajectory','Hayek: Road to Serfdom chapter on democracy')","@('definitional dodge')","ussr-not-real-socialism"),
    @("market-failures-require-socialism","human-nature-incentives","Market Failures Require Socialism","Externalities prove markets fail — socialism fixes them.","Pigouvian taxes, property rights (Coase), and markets for pollution permits address externalities without abolishing private ownership.","@('Coase Theorem applications','Cap-and-trade success stories')","@('false dichotomy')","green-new-deal-growth"),
    @("economic-democracy","nordic-democratic-socialism","Economic Democracy Replaces Exploitation","Workers voting on production replaces capitalist exploitation.","Democratic votes over capital allocation recreate calculation and knowledge problems at firm level. Political majorities can expropriate minorities.","@('Mises calculation problem applied to worker councils','Yugoslav self-management stagnation')","@('category error')","calculation-impossible"),
    @("poverty-racism-only","wealth-inequality-mobility","Poverty Is Only Structural Racism","Capitalism and racism are the same system.","Racial gaps are real but narrowing where markets expand opportunity (black business formation, Hispanic income growth). Institutional reform + economic freedom outperform collectivist redistribution alone.","@('Census ethnic income trend data','SBA minority business growth statistics')","@('single-cause fallacy')","wealth-inequality-broken"),
    @("open-borders-socialist","founding-principles","Borders Are Capitalist Oppression","Open borders are required for justice.","Sovereignty and rule of law enable the welfare state socialists defend. Unrestricted migration without assimilation strains public goods — Bastiat's seen/unseen applies.","@('Fiscal impact studies on migration','Bastiat: What Is Seen and What Is Not Seen')","@('internally inconsistent')","constitution-limits")
)

foreach ($m in $more) {
    $claims += New-Claim $m[0] $m[1] $m[2] $m[3] $m[4] ($m[5] -replace "@\('|'\)" -split "', '" | ForEach-Object { $_ -replace "^'|'$", "" }) ($m[6] -replace "@\('|'\)" -split "', '" | ForEach-Object { $_ -replace "^'|'$", "" }) @(&$src "Primary source" "https://www.census.gov" "government") $m[7] @($m[7]) ($m[8] -split ",")
}

$output = @{ version = "1.0.0"; updatedAt = "2026-07-04"; claims = $claims }
$json = $output | ConvertTo-Json -Depth 10
$outPath = Join-Path $PSScriptRoot "..\assets\data\claims_seed.json"
$json | Set-Content -Path $outPath -Encoding UTF8
Write-Host "Generated $($claims.Count) claims -> $outPath"